

set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_InVideoFormat_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_OutVideoFormat_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_width_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_height_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_K11_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_K12_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_K13_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_K21_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_K22_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_K23_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_K31_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_K32_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_K33_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_ROffset_V_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_GOffset_V_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_BOffset_V_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_ClampMin_V_reg[*]]
set_false_path -from [get_cells v_csc_CTRL_s_axi_U/int_HwReg_ClipMax_V_reg[*]]
