
#ifndef _V_MIX_CONFIG_H_
#define _V_MIX_CONFIG_H_

#define SAMPLES_PER_CLOCK       2
#define MAX_COLS                3840
#define MAX_ROWS                2160
#define MAX_DATA_WIDTH          8
#define NR_COMPONENTS           3
#define NR_LAYERS				5
#define NR_LAYERS_MIN_1			4
#define BITS_PER_SAMPLE         (NR_COMPONENTS*MAX_DATA_WIDTH)
#define BITS_PER_CLOCK          (BITS_PER_SAMPLE*SAMPLES_PER_CLOCK)
#define AXIMM_DATA_WIDTH		(32*SAMPLES_PER_CLOCK*2)
#define AXIMM_NUM_OUTSTANDING   16

#define LAYER1_ALPHA			true 
#define LAYER2_ALPHA			true 
#define LAYER3_ALPHA			true 
#define LAYER4_ALPHA			true 
#define LAYER5_ALPHA			false 
#define LAYER6_ALPHA			false 
#define LAYER7_ALPHA			false 

#define LAYER1_UPSAMPLE			false 
#define LAYER2_UPSAMPLE			false 
#define LAYER3_UPSAMPLE			false 
#define LAYER4_UPSAMPLE			false 
#define LAYER5_UPSAMPLE			false 
#define LAYER6_UPSAMPLE			false 
#define LAYER7_UPSAMPLE			false 

#define LAYER1_MAX_WIDTH		1920 
#define LAYER2_MAX_WIDTH		1920 
#define LAYER3_MAX_WIDTH		1920 
#define LAYER4_MAX_WIDTH		1920 
#define LAYER5_MAX_WIDTH		1920 
#define LAYER6_MAX_WIDTH		1920 
#define LAYER7_MAX_WIDTH		1920 

#define OUTPUT_VIDEO_FORMAT		0 
#define INPUT_VIDEO_FORMAT		OUTPUT_VIDEO_FORMAT
#define LAYER1_VIDEO_FORMAT		12 
#define LAYER2_VIDEO_FORMAT		12 
#define LAYER3_VIDEO_FORMAT		28 
#define LAYER4_VIDEO_FORMAT		26 
#define LAYER5_VIDEO_FORMAT		10 
#define LAYER6_VIDEO_FORMAT		10 
#define LAYER7_VIDEO_FORMAT		10 

#define LAYER1_INTF_TYPE		0 
#define LAYER2_INTF_TYPE		0 
#define LAYER3_INTF_TYPE		0 
#define LAYER4_INTF_TYPE		0 
#define LAYER5_INTF_TYPE		0 
#define LAYER6_INTF_TYPE		0 
#define LAYER7_INTF_TYPE		0 

#define LAYER1_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER1_VIDEO_FORMAT)
#define LAYER2_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER2_VIDEO_FORMAT)
#define LAYER3_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER3_VIDEO_FORMAT)
#define LAYER4_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER4_VIDEO_FORMAT)
#define LAYER5_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER5_VIDEO_FORMAT)
#define LAYER6_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER6_VIDEO_FORMAT)
#define LAYER7_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER7_VIDEO_FORMAT)

#define LOGO_LAYER				false
#define MAX_LOGO_WIDTH			64
#define MAX_LOGO_HEIGHT			64
#define LOGO_TRANSPARENCY_COLOR false
#define LOGO_PIXEL_ALPHA		false

#define PLANE0_STREAM_DEPTH     240

#endif
